---
test_name: Check server responds with updated data
includes:
  - !include common.yaml

stages:
  - name: Send message, expect it to be echoed back
    request:
      method: GET
      url: "{base_url}/pet/findByStatus"
      params:
        status: available
    response:
      status_code: 200